zsh_cache_home="${XDG_CACHE_HOME:-${HOME}/.cache}"/zsh && mkdir -p "${zsh_cache_home}"
zsh_config_home="${XDG_CONFIG_HOME:-${HOME}/.config}"/zsh && mkdir -p "${zsh_config_home}"
zsh_data_home="${XDG_DATA_HOME:-${HOME}/.local/share}"/zsh && mkdir -p "${zsh_data_home}"

fpath=(
  "${zsh_config_home}"/functions
  ${fpath}
)

HISTSIZE=10000

autoload -Uz zle-line-finish && zle -N zle-line-finish
autoload -Uz zle-line-init && zle -N zle-line-init
