zsh_cache_home="${XDG_CACHE_HOME:-${HOME}/.cache}"/zsh && mkdir -p "${zsh_cache_home}"
zsh_config_home="${XDG_CONFIG_HOME:-${HOME}/.config}"/zsh && mkdir -p "${zsh_config_home}"
zsh_data_home="${XDG_DATA_HOME:-${HOME}/.local/share}"/zsh && mkdir -p "${zsh_data_home}"

fpath=(
  "${zsh_config_home}"/functions
  ${fpath}
)

HISTFILE="${zsh_data_home}"/histfile
HISTSIZE=10000
SAVEHIST=10000

autoload -Uz preferred-util
preferred-util EDITOR nvim vim vi
preferred-util PAGER less more
preferred-util VISUAL nvim vim vi

autoload -Uz zle-line-finish && zle -N zle-line-finish
autoload -Uz zle-line-init && zle -N zle-line-init

bindkey -e

autoload -Uz promptinit && promptinit
prompt marcelsiegert
